spring:
  application:
    name: BDASGA2

  datasource:
    url: jdbc:mysql://localhost:3306/schooldb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: springuser
    password: Password123
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 8080